USE DEMO

CREATE TABLE Cities
(
	CityID INT IDENTITY PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
)

CREATE TABLE Customers
(
		CustomerID INT IDENTITY PRIMARY KEY,
		Name VARCHAR(50) NOT NULL,
		Birthday DATE NOT NULL,
		CityID INT FOREIGN KEY
		REFERENCES Cities(CityID) NOT NULL
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Items
(
	ItemID INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	ItemTypeID INT FOREIGN KEY
	REFERENCES ItemTypes(ItemTypeID) NOT NULL
)

CREATE TABLE Orders
(
	OrderID INT PRIMARY KEY IDENTITY,
	CustomerID INT FOREIGN KEY
	REFERENCES Customers(CustomerID) NOT NULL
)

CREATE TABLE OrderItems
(
	OrderID INT,
	ItemID INT,
	CONSTRAINT PK_OrdersItems
	PRIMARY KEY (OrderID, ItemID),
	CONSTRAINT FK_OrdersItems_Orders
	FOREIGN KEY (OrderID)
	REFERENCES Orders(OrderID),
	CONSTRAINT FK_OrdersItems_Items
	FOREIGN KEY (ItemID)
	REFERENCES Items(ItemID)
)

